name: Setup AWS Infra

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    # inputs:
    #   ec2-name:
    #     description: EC2 Instance
    #     required: true
    #     default: "App"
    #     type: string
env:
  AWS_REGION: "eu-north-1"

jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Apply
        id: apply
        env:
          TF_VAR_ec2_Name: "${{github.event.inputs.ec2-name}}"
        run: terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
